project_id = "fmljyldunjdxpbqetdlu"

[functions.paystack-initialize]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false

[functions.paystack-verify]
verify_jwt = false

[functions.subscription-reminder]
verify_jwt = false

[functions.fulfill-data-order]
verify_jwt = true

[functions.sync-swift-plans]
verify_jwt = true
