// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fmljyldunjdxpbqetdlu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtbGp5bGR1bmpkeHBicWV0ZGx1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg5MjY1NzcsImV4cCI6MjA4NDUwMjU3N30.tR52NXTM4Anei76LeGw51zjsxmkWgN3NQ2lWBLrUP2Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});